name: sixam_mart
description: A Multi-vendor Food. Grocery, eCommerce, Pharmacy & Parcel service.
publish_to: 'none'
version: 3.0.8+8

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  audioplayers: ^0.20.1
  card_swiper: ^3.0.1
  carousel_slider: ^4.0.0
  connectivity: ^3.0.6
  country_code_picker: ^3.0.0
  dotted_border: ^2.0.0+1
  expandable_bottom_sheet: ^1.1.1+1
  fast_cached_network_image: ^1.2.0
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  flutter:
    sdk: flutter
  flutter_animarker: ^3.2.0
  flutter_facebook_auth: ^5.0.1
  flutter_html: ^3.0.0-alpha.5
  flutter_inappwebview: ^5.7.1
  flutter_local_notifications: ^17.1.2
  flutter_slidable: ^3.0.0
  flutter_typeahead: ^4.3.7
  flutter_widget_from_html: ^0.8.5
  geolocator: ^12.0.0
  get: ^4.6.5
  google_maps_flutter: ^2.1.5
  google_maps_flutter_web: ^0.5.8
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4
  http: ^0.13.4
  image_compression_flutter: ^1.0.2
  image_picker: ^1.1.2
  image_picker_ios: ^0.8.5+6
  intl: ^0.19.0
  just_the_tooltip: ^0.0.12
  meta_seo: ^3.0.5
  path_provider: ^2.0.8
  phone_numbers_parser: ^8.3.0
  photo_view: ^0.15.0
  pin_code_fields: ^8.0.1
  pointer_interceptor: ^0.10.1+1
  share_plus: ^9.0.0
  shared_preferences: ^2.0.11
  shimmer_animation: ^2.1.0+1
  sign_in_with_apple: ^6.1.1
  universal_html: ^2.0.8
  url_launcher: ^6.1.2
  url_strategy: ^0.2.0
  youtube_player_iframe: ^3.1.0

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
